export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const UPVOTE_ARTICLE = 'UPVOTE_ARTICLE'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'